const iconList = {
  Bathroom: [
    { name: "Bath Robe", path: "/assets/icons/Bathroom/bath-robe.png" },
    { name: "Comb", path: "/assets/icons/Bathroom/comb.png" },
    { name: "Flip Flops", path: "/assets/icons/Bathroom/flip-flops.png" },
    { name: "Mouthwash", path: "/assets/icons/Bathroom/mouthwash.png" },
    { name: "Razor", path: "/assets/icons/Bathroom/razor.png" },
    { name: "Sponge", path: "/assets/icons/Bathroom/sponge.png" },
    { name: "Toothbrush", path: "/assets/icons/Bathroom/toothbrush.png" },
    { name: "Toothpaste", path: "/assets/icons/Bathroom/toothpaste.png" },
    { name: "Towel", path: "/assets/icons/Bathroom/towel.png" },
    { name: "Trimmer", path: "/assets/icons/Bathroom/trimmer.png" },
  ],
  Bedroom: [
    { name: "Alarm Clock", path: "/assets/icons/Bedroom/alarm-clock.png" },
    { name: "Bolster", path: "/assets/icons/Bedroom/bolster.png" },
    { name: "Fan", path: "/assets/icons/Bedroom/fan.png" },
    { name: "Mirror", path: "/assets/icons/Bedroom/mirror.png" },
    { name: "Pillows", path: "/assets/icons/Bedroom/pillows.png" },
    { name: "Sleeping Mask", path: "/assets/icons/Bedroom/sleeping-mask.png" },
    { name: "Sleeping Pills", path: "/assets/icons/Bedroom/sleeping-pills.png" },
    { name: "Table Lamp", path: "/assets/icons/Bedroom/table-lamp.png" },
    { name: "Wall Clock", path: "/assets/icons/Bedroom/wall-clock.png" },
  ],
  Kitchen: [
    { name: "Bowls", path: "/assets/icons/Kitchen/bowls.png" },
    { name: "Cutlery", path: "/assets/icons/Kitchen/cutlery.png" },
    { name: "Frying Pan", path: "/assets/icons/Kitchen/frying-pan.png" },
    { name: "Measuring Spoons", path: "/assets/icons/Kitchen/measuring-spoons.png" },
    { name: "Mixer", path: "/assets/icons/Kitchen/mixer.png" },
    { name: "Oven Mitt", path: "/assets/icons/Kitchen/oven-mitt.png" },
    { name: "Pepper", path: "/assets/icons/Kitchen/pepper.png" },
    { name: "Recipe", path: "/assets/icons/Kitchen/recipe.png" },
    { name: "Rolling Pin", path: "/assets/icons/Kitchen/rolling-pin.png" },
    { name: "Tupperware", path: "/assets/icons/Kitchen/tupperware.png" },
  ],
  "Living Room": [
    { name: "Speakers", path: "/assets/icons/Living Room/speakers.png" },
    { name: "Frame", path: "/assets/icons/Living Room/frame.png" },
    { name: "Curtain", path: "/assets/icons/Living Room/curtain.png" },
    { name: "Circuit Board", path: "/assets/icons/Living Room/circuit-board.png" },
    { name: "Carpet", path: "/assets/icons/Living Room/carpet.png" },
  ],
  Patio: [
    { name: "Shovel", path: "/assets/icons/Patio/shovel.png" },
    { name: "Lawn Mower", path: "/assets/icons/Patio/lawn-mower.png" },
    { name: "Watering Can", path: "/assets/icons/Patio/watering-can.png" },
  ],
  Office: [
    { name: "Stationery", path: "/assets/icons/Office/stationery.png" },
    { name: "Printer", path: "/assets/icons/Office/printer.png" },
    { name: "Binder", path: "/assets/icons/Office/binder.png" },
    { name: "Calculator", path: "/assets/icons/Office/calculator.png" },
    { name: "Calendar", path: "/assets/icons/Office/calendar.png" },
    { name: "Desk Lamp", path: "/assets/icons/Office/desk-lamp.png" },
    { name: "Filling Cabinet", path: "/assets/icons/Office/filling-cabinet.png" },
  ],
};

export default iconList;
